# Generated by Django 6.0.2 on 2026-03-20 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Campus or nearby address', max_length=200)),
                ('business_type', models.CharField(max_length=50, verbose_name=[('student seller', 'Student Seller'), ('restaurant', 'Restaurant')])),
                ('description', models.TextField(blank=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurant_logos/')),
                ('ssm_registration', models.CharField(blank=True, max_length=50)),
                ('pickup_locations', models.TextField(blank=True, help_text='Comma-separated pickup points, e.g. Hostel Lobby, Library Entrance')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'BUSINESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'business profile',
                'verbose_name_plural': 'business profiles',
            },
        ),
        migrations.DeleteModel(
            name='RestaurantProfile',
        ),
    ]
