# Generated by Django 6.0.2 on 2026-04-18 09:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_businessprofile_is_live_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slots_number', models.IntegerField()),
                ('restaurant_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='cuisine_type',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Public ID'),
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='pickup_locations',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Public ID'),
        ),
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='users.cuisine'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='pickup_locations',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='users.pickuplocation'),
        ),
    ]
