# Generated by Django 6.0.2 on 2026-05-25 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cuisine_pickuplocation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuisine',
            options={'ordering': ['name'], 'verbose_name': 'cuisine', 'verbose_name_plural': 'cuisines'},
        ),
        migrations.AlterModelOptions(
            name='pickuplocation',
            options={'ordering': ['name'], 'verbose_name': 'pickup location', 'verbose_name_plural': 'pickup locations'},
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='restaurant_number',
        ),
        migrations.RemoveField(
            model_name='cuisine',
            name='slots_number',
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('student', 'Student Seller'), ('restaurant', 'Restaurant')], default='restaurant', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='default_pickup_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('BUSINESS', 'business'), ('CUSTOMER', 'customer')], default='CUSTOMER', max_length=20),
        ),
        migrations.DeleteModel(
            name='BaseProfile',
        ),
    ]
