# Generated by Django 6.0.2 on 2026-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cuisine_options_alter_pickuplocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'admin'), ('BUSINESS', 'business'), ('CUSTOMER', 'customer')], max_length=20, null=True),
        ),
    ]
